services:
  replica1:
    image: ah-rm
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    networks:
      - ah
    command: :8000
  replica2:
    image: ah-rm
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    networks:
      - ah
    command: :8001
  replica3:
    image: ah-rm
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    networks:
      - ah
    command: :8002
  frontend1:
    image: ah-fe
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - ah
    ports:
      - "1400:1400"
    command: :1400 replica1:8000 replica2:8001 replica3:8002
    depends_on:
      - "replica1" 
      - "replica2" 
      - "replica3"
  frontend2:
    image: ah-fe
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - ah
    ports:
      - "1401:1401"
    command: :1401 replica1:8000 replica2:8001 replica3:8002
    depends_on:
      - replica1 
      - replica2 
      - replica3
networks:
  ah: {}